Update __init__.py
pip install is failing with:

SyntaxError: Non-ASCII character '\xc3' in file /home/platform/taiga-scripts/taiga-contrib-github-auth/back/taiga_contrib_github_auth/__init__.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

due to this